# Generated by Django 4.2.7 on 2023-11-06 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to=settings.AUTH_USER_MODEL),
        ),
    ]
