# Generated by Django 4.2.7 on 2023-11-06 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_family_user'),
        ('articleapp', '0002_alter_newarticle_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarticle',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='profileapp.family'),
            preserve_default=False,
        ),
    ]
