# Generated by Django 4.2.7 on 2023-11-06 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0003_alter_newarticle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarticle',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
